portfolio/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_app.urls')),
]

portfolio/portfolio_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('students/', views.StudentListView.as_view(), name= 'students'),
        path('students/<int:pk>', views.StudentDetailView.as_view(), name= 'student-detail'),
        path('portfolios/', views.PortfolioListView.as_view(), name= 'portfolios'),
        path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name= 'portfolio-detail'),
        path('projects/', views.ProjectListView.as_view(), name= 'projects'),
        path('project/<int:pk>', views.ProjectDetailView.as_view(), name= 'project-detail'),
        path('portfolio/<int:pk>/create_project', views.CreateProjectView.as_view(), name='project-form'),
        path('portfolio/<int:pk>/update', views.update_portfolio, name='update-portfolio'),
        path('project/<int:pk>/delete', views.delete_project, name='delete-project'),
        path('project/<int:pk>/update', views.update_project, name='update-project'),
]

portfolio/portfolio_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Portfolio(models.Model):
    title = models.CharField(max_length=200, default=timezone.now)
    contact_email = models.CharField(max_length=200, default=timezone.now)
    is_active = models.BooleanField(default=False)
    about = models.TextField(blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('portfolio-detail', args=[str(self.id)])


class Project(models.Model):
    title = models.CharField(max_length=200, default=timezone.now)
    description = models.TextField()
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, default = None, null = True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('project-detail', args=[str(self.id)])

class Student(models.Model):
    #List of choices for majrs
    MAJOR =(
        ('CSCI-BS', 'BS in Computer Science'),
        ('CPEN-BS', 'BS in Computer Engineering'),
        ('BIGD-BI', 'BI in Game Design and Development'),
        ('BICS-BI', 'BI in Computer Science'),
        ('BISC-BI', 'BI in Computer Security'),
        ('CSCI-BA', 'BA in Computer Science'),
        ('DASE-BS', 'BS in Data Analytics and Systems Engineering')
        
    )#end of major

    name = models.CharField(max_length=200)
    email = models.CharField("UCCS Email", max_length=200)
    major = models.CharField(max_length=200, choices=MAJOR)#, blank = True)
    portfolio = models.OneToOneField(Portfolio, on_delete=models.CASCADE, null = True, default = None, blank = True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('student-detail', args=[str(self.id)])

portfolio/portfolio_app/forms.py
from django.forms import ModelForm
from .models import Project, Portfolio, Student

#create class for project form
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields =('title', 'description', 'portfolio')

#create class for portfolio form
class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields =('title', 'contact_email', 'is_active', 'about')

portfolio/portfolio_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.views import generic
from .models import Student
from django.urls import reverse_lazy
from .models import Portfolio
from .models import Project
from .forms import ProjectForm, PortfolioForm

# Create your views here.
def index(request):
    student_active_portfolios = Student.objects.select_related('portfolio').all().filter(portfolio__is_active=True)
    print("active portfolio query set", student_active_portfolios)
    return render( request, 'portfolio_app/index.html', {'student_active_portfolios':student_active_portfolios})

def delete_project(request, pk):
    proj = get_object_or_404(Project, pk=pk)

    if request.method == 'POST':
        portfolio = proj.portfolio.id
        proj.delete()
        messages.success(request, "Deleted!")
        return redirect('portfolio-detail', pk=portfolio)

    return render(request, 'portfolio_app/confirm_delete.html', {'proj':proj})

def update_project(request, pk):
    proj = get_object_or_404(Project, pk=pk)

    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=proj)
        form.save()
        return redirect('project-detail', pk=pk)
    else:
        form = ProjectForm(instance=proj)
    return render(request, "portfolio_app/project_form.html", {'form': form})

def update_portfolio(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)

    if request.method == 'POST':
        form = PortfolioForm(request.POST, instance=portfolio)
        form.save()
        return redirect('portfolio-detail', pk=pk)
    else:
        form = PortfolioForm(instance=portfolio)
    return render(request, "portfolio_app/project_form.html", {'form': form})



class StudentListView(generic.ListView):
    model = Student

class StudentDetailView(generic.DetailView):
    model = Student

class PortfolioListView(generic.ListView):
    model = Portfolio

class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    def get_context_data(self, **kwargs):
        projects = Project.objects.all()
        student_portfolio_projects = []
        for project in projects:
            if project.portfolio.id == self.object.id:
                student_portfolio_projects.append(project)
        context = super(PortfolioDetailView, self).get_context_data( **kwargs)
        context["student_portfolio_projects"] = student_portfolio_projects
        return context

    def __str__(self):
        return self.id

class UpdateProjectView(generic.edit.FormView):
    template_name = "portfolio_app/project_form.html"
    form_class = ProjectForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class CreateProjectView(generic.edit.FormView):
    template_name = "portfolio_app/project_form.html"
    form_class = ProjectForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ProjectListView(generic.ListView):
    model = Project

class ProjectDetailView(generic.DetailView):
    model = Project

portfolio/portfolio_app/templates/portfolio_app/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>UCCS CS Students</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>


<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light lead">
<img src="{% static 'images/uccs.gif' %}" />
<div class="container-fluid">
<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
<div class="navbar-nav">
<a class="nav-link" href="{% url 'index' %}">Home</a>
<a class="nav-link" href="{% url 'students' %}">Students</a>
</div>
</div>
</div>
</nav>


<!-- add block content from html template -->
{% block content %}


{% endblock %}
</body>
</html>

portfolio/portfolio_app/templates/portfolio_app/confirm_delete.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h2>Are you sure you want to delete this item? {{proj.title}}</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete it</button>
        <a href="{% url 'project-detail' proj.id%}">Cancel</a>
    </form>
{% endblock %}

<a href="{% url 'delete_project' proj.pk %}">Delete</a>

portfolio/portfolio_app/templates/portfolio_app/index.html
<!-- inherit from base.html -->
{% extends 'portfolio_app/base_template.html' %}


<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Computer Science Student Portfolios</h1>


<h2>List of Students with Active Portfolios</h2>
<ul class="list-group">
{% for i in student_active_portfolios %}
<li class="list-group-item">Name: {{i.name}}
<p><strong>Portfolio:{{ i.portfolio.title }}
<a class="btn btn-primary" href="{{ i.portfolio.get_absolute_url }}" role="button">View</a>
</li>
{% endfor %}
</ul>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/portfolio_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Portfolio Title: {{ portfolio.title }}</h1>
<a class="btn btn-info" href="{{portfolio.get_absolute_url}}/update" role="button">Edit</a>

<p><strong>Contact Email:</strong> {{ portfolio.contact_email }}</p>
<p><strong>Is Active:</strong> {{ portfolio.is_active }}</p>
<p><strong>About:</strong> {{ portfolio.about }}</p>

<h2>Project List</h2>
<ul class="list-group">
{% for i in student_portfolio_projects %}
<li class="list-group-item"><strong>Project: {{i.title}}
<p>Description: {{i.description}}
<a class="btn btn-primary" href="{{i.get_absolute_url}}" role="button">View</a>
<a class="btn btn-danger" href="{{i.get_absolute_url}}/delete">Delete</a>
<a class="btn btn-info" href="{{i.get_absolute_url}}/update" role="button">Edit</a>
</li>
{% endfor %}
</ul>
<a class="btn btn-primary" href="{% url 'project-form' portfolio.id %}" role="button">New Project</a>

{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/portfolio_list.html
{% extends 'portfolio_app/base_template.html' %}


{% block content %}
<h1>Student List</h1>
{% if student_list %}
<ul>
{% for student in student_list %}
<li>
<a href="{{ student.get_absolute_url }}">{{ student.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no students registered.</p>
{% endif %}
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_add_success.html
Success!

portfolio/portfolio_app/templates/portfolio_app/project_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Project Title: {{ project.title }}</h1>

<a class="btn btn-danger" href="{{project.get_absolute_url}}/delete">Delete Project</a>
<a class="btn btn-info" href="{{project.get_absolute_url}}/update">Update Project</a>
<p><strong>Description:</strong> {{ project.description }}</p>
<p><strong>Portfolio:</strong><a href={{project.portfolio.get_absolute_url}}> {{ project.portfolio }}</a>


{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_form.html
<!-- inherit from base.html -->
{% extends 'portfolio_app/base_template.html' %}


<!-- Replace block content in base_template.html -->
{% block content %}


<form action="" method="POST">


{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" name="Submit">
</form>


{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Student List</h1>
{% if student_list %}
<ul>
{% for project in project_list %}
<li>
<a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no projects registered.</p>
{% endif %}
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/student_detail.html
{% extends 'portfolio_app/base_template.html' %}


{% block content %}
<h1>Student Name: {{ student.name }}</h1>


<p><strong>Email:</strong> {{ student.email }}</p>
<p><strong>Major:</strong> {{ student.major }}</p>
<p><strong>Portfolio:<a href="{{ student.portfolio.get_absolute_url }}">{{ student.portfolio.title }} </a>
<a class="btn btn-info" href="{{student.portfolio.get_absolute_url}}/update" role="button">Edit</a>

{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/student_list.html
{% extends 'portfolio_app/base_template.html' %}


{% block content %}
<h1>Student List</h1>
{% if student_list %}
<ul>
{% for student in student_list %}
<li>
<a href="{{ student.get_absolute_url }}">{{ student.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no students registered.</p>
{% endif %}
{% endblock %}